name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.4
  date_picker_timeline: ^1.2.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.18.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^24.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/
